import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PrismaClient} from '@prisma/client';
import {buildApp} from '../apps/api/src/app.js';
import {hashPassword} from '../apps/api/src/auth.js';
import {extractText,extractDocument} from '../apps/api/src/invoice-extract.js';
import {readConnection} from '../apps/api/src/connections.js';
assert.match(process.env.DATABASE_URL??'',/(?:_test|schema=erp_test)/);
process.env.NODE_ENV='test';process.env.WEB_ORIGIN='http://localhost:5173';process.env.ERP_TEST_MODE='true';process.env.INTEGRATION_ENCRYPTION_KEY='18'.repeat(32);
const db=new PrismaClient(),app=await buildApp(db,false),prefix='invoice-'+Date.now(),password='invoice-test-password';let cookie='';
async function call(path:string,body?:any,status=200,method='POST'){const r=await app.inject({method:body===undefined?'GET':method as any,url:'/api'+path,headers:{cookie,origin:process.env.WEB_ORIGIN!,'content-type':'application/json','idempotency-key':randomUUID()},payload:body});assert.equal(r.statusCode,status,`${path}: ${r.body}`);return r.json();}
await test('Invoice intake, review and Shopify matching integrity',async t=>{
  try{
    const admin=await db.user.create({data:{email:prefix+'@test.invalid',name:'Invoice admin',role:'ADMIN',passwordHash:hashPassword(password)}});const login=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:admin.email,password}});cookie=String(login.headers['set-cookie']).split(';')[0];
    const family=await call('/component-families',{name:prefix,category:'MEMORY'}),a=await call('/skus',{code:prefix+'-32',name:'Kingston Fury DDR5 32GB 6000 Black',familyId:family.id,trackingMode:'SERIALIZED',barcodes:[prefix+'-EAN']}),b=await call('/skus',{code:prefix+'-16',name:'Kingston Fury DDR5 16GB 6000 Black',familyId:family.id,trackingMode:'SERIALIZED'});
    const supplier=await call('/suppliers',{code:prefix,name:'Test distributor',email:prefix+'@supplier.invalid'});
    const shop=prefix+'.myshopify.com',variant={id:'gid://shopify/ProductVariant/901',title:'32GB / Black',sku:a.code,barcode:prefix+'-EAN',product:{id:'gid://shopify/Product/801',title:'Kingston FURY Beast 32 GB DDR5 kit',handle:'fury-kit',vendor:'Kingston',productType:'Memory',status:'ACTIVE'}};
    let mapping:any,invoice:any;
    await t.test('catalogue exact matches remain suggestions until confirmed; refresh preserves decisions',async()=>{
      await call('/matching/shopify/import',{shopDomain:shop,exportedAt:new Date().toISOString(),complete:true,variants:[variant]});mapping=(await call('/matching')).variants.find((v:any)=>v.shopDomain===shop);assert.equal(mapping.skuId,null);assert.equal(mapping.candidates[0].id,a.id);
      await call('/matching/shopify/'+mapping.id,{skuId:a.id},200,'PATCH');await call('/matching/shopify/import',{shopDomain:shop,exportedAt:new Date().toISOString(),complete:true,variants:[{...variant,product:{...variant.product,title:'Renamed Shopify title'}}]});mapping=(await call('/matching')).variants.find((v:any)=>v.shopDomain===shop);assert.equal(mapping.skuId,a.id);assert.ok(mapping.confirmedAt);
      await call('/matching/shopify/import',{shopDomain:shop,exportedAt:'2020-01-01T00:00:00.000Z',complete:true,variants:[]},409);
    });
    await t.test('invoice extraction keeps numbers and original files; repeated import is deduplicated',async()=>{
      const csv=`description,supplierCode,quantity,unitCost,lineTotal\nKF560C36BBEK2-32 memory kit,${a.code},2,150.00,300.00\n`,body={filename:'supplier-invoice.csv',base64:Buffer.from(csv).toString('base64')};const first=await call('/invoices/upload',body),second=await call('/invoices/upload',body);assert.equal(first.id,second.id);assert.equal(second.duplicate,true);invoice=await call('/invoices/'+first.id);assert.equal(invoice.lines[0].quantity,2);assert.equal(invoice.lines[0].skuId,a.id);assert.equal(invoice.lines[0].confirmed,false);assert.equal(invoice.files.length,1);assert.ok(invoice.issues.length);
      await call('/invoices/'+invoice.id+'/approve',{version:invoice.version},400);
    });
    const edit=()=>({version:invoice.version,supplierId:supplier.id,invoiceNumber:prefix,invoiceDate:'2026-09-05',dueDate:'2026-09-20',currency:'NZD',subtotal:300,tax:45,freight:0,total:345,purchaseOrderId:null,lines:invoice.lines.map((l:any)=>({description:l.description,supplierCode:l.supplierCode,barcode:l.barcode,quantity:l.quantity,unitCost:Number(l.unitCost),lineTotal:Number(l.lineTotal),skuId:a.id,confirmed:true}))});
    await t.test('review catches stale edits, incorrect totals and unconfirmed matches',async()=>{
      const body=edit();await call('/invoices/'+invoice.id,body,200,'PATCH');await call('/invoices/'+invoice.id,body,409,'PATCH');invoice=await call('/invoices/'+invoice.id);assert.equal(invoice.lines[0].confirmed,false,'supplier change clears confirmation');await call('/invoices/'+invoice.id,{...edit(),total:999},200,'PATCH');invoice=await call('/invoices/'+invoice.id);await call('/invoices/'+invoice.id+'/approve',{version:invoice.version},400);await call('/invoices/'+invoice.id,edit(),200,'PATCH');invoice=await call('/invoices/'+invoice.id);assert.equal(invoice.issues.length,0);
    });
    await t.test('approval learns supplier-specific aliases and freezes the reviewed match without receiving stock',async()=>{
      const before=await db.inventoryTransaction.count();await call('/invoices/'+invoice.id+'/approve',{version:invoice.version,rememberAliases:true});invoice=await call('/invoices/'+invoice.id);assert.equal(invoice.status,'APPROVED');assert.equal(invoice.lines[0].matchSnapshot.sku.code,a.code);assert.equal(invoice.lines[0].matchSnapshot.shopify[0].productTitle,'Renamed Shopify title');assert.equal(await db.inventoryTransaction.count(),before);
      await call('/invoices/'+invoice.id,edit(),409,'PATCH');const aliases=(await call('/matching')).aliases.filter((x:any)=>x.supplierId===supplier.id);assert.equal(aliases.length,2);
      await call('/matching/shopify/'+mapping.id,{skuId:b.id},200,'PATCH');const saved=await call('/invoices/'+invoice.id);assert.equal(saved.lines[0].matchSnapshot.shopify[0].productTitle,'Renamed Shopify title');assert.equal(saved.lines[0].matchSnapshot.sku.id,a.id);
      const po=await call('/invoices/'+invoice.id+'/create-po',{number:prefix+'-PO'});assert.equal(po.status,'DRAFT');assert.equal(await db.inventoryTransaction.count(),before);await call('/invoices/'+invoice.id+'/create-po',{number:prefix+'-PO2'},409);
    });
    await t.test('conflicting identifiers cannot silently choose a SKU and duplicate invoice numbers are blocked',async()=>{
      const body={filename:'different-file.txt',base64:Buffer.from(`Invoice No: ${prefix}\nInvoice date: 05/09/2026\nAnother invoice name 2 150.00 300.00\nSubtotal 300.00\nGST 45.00\nFreight 0.00\nTotal 345.00`).toString('base64')};const newInvoice=await call('/invoices/upload',body),oldInvoice=invoice;invoice=await call('/invoices/'+newInvoice.id);await call('/invoices/'+invoice.id,edit(),200,'PATCH');invoice=await call('/invoices/'+invoice.id);await call('/invoices/'+invoice.id,edit(),200,'PATCH');invoice=await call('/invoices/'+invoice.id);await call('/invoices/'+invoice.id+'/approve',{version:invoice.version},409);invoice=oldInvoice;
      await call('/matching/aliases',{supplierId:supplier.id,skuId:b.id,kind:'CODE',value:a.code});const csv=`description,supplierCode,quantity,unitCost,lineTotal\nconflicting identifiers,${a.code},1,150.00,150.00\n`;const conflict=await call('/invoices/upload',{filename:'conflict.csv',base64:Buffer.from(csv).toString('base64')});let d=await call('/invoices/'+conflict.id);const header={...edit(),version:d.version,lines:[{description:'conflict',supplierCode:a.code,barcode:null,quantity:1,unitCost:150,lineTotal:150,skuId:null,confirmed:false}]};await call('/invoices/'+d.id,header,200,'PATCH');d=await call('/invoices/'+d.id);assert.equal(d.lines[0].suggestion.ambiguous,true);assert.equal(d.lines[0].suggestion.suggestedSkuId,null);
    });
    await t.test('Shopify credentials are verified, encrypted and used by subsequent reads',async()=>{
      const original=globalThis.fetch;globalThis.fetch=async(url:any,options:any)=>{assert.match(String(url),/\.myshopify\.com\/admin\/api\//);assert.equal(options.headers['X-Shopify-Access-Token'],'test-shopify-token-123');return new Response(JSON.stringify({data:{shop:{name:'Test Store',myshopifyDomain:shop},currentAppInstallation:{accessScopes:[{handle:'read_products'}]}}}),{status:200});};
      try{await call('/matching/shopify/connect',{domain:shop,accessToken:'test-shopify-token-123'});const row=await db.integrationConnection.findUniqueOrThrow({where:{provider:'SHOPIFY'}});assert.ok(!row.encrypted.includes('test-shopify-token'));assert.equal((await readConnection(db,'SHOPIFY')).accessToken,'test-shopify-token-123');const status=await call('/integrations/status');assert.equal(status.shopify.domain,shop);assert.ok(!JSON.stringify(status).includes('test-shopify-token'));await call('/matching/shopify/check',{});}finally{globalThis.fetch=original;}
    });
    await t.test('email consent rejects fabricated callbacks and import does not mark messages read',async()=>{
      await call('/mailbox/configure',{provider:'GMAIL',clientId:'test-client',clientSecret:'secret',folder:'Invoices',since:'2026-09-01',senders:[supplier.email]});const auth=await app.inject({method:'POST',url:'/api/mailbox/authorize',headers:{cookie,origin:process.env.WEB_ORIGIN!,'content-type':'application/json'},payload:{}});assert.equal(auth.statusCode,200);assert.match(auth.json().url,/gmail.readonly/);const u=new URL(auth.json().url),oauthCookie=String(auth.headers['set-cookie']).split(';')[0];const invalid=await app.inject({url:'/api/mailbox/callback?state=fake&code=fake'});assert.equal(invalid.statusCode,400);
      const original=globalThis.fetch;globalThis.fetch=async(url:any,options:any)=>{const s=String(url);if(s.includes('oauth2.googleapis.com/token'))return new Response(JSON.stringify({access_token:'mail-access',refresh_token:'mail-refresh'}));assert.equal(options.method,undefined,'mail reads use GET');if(s.endsWith('format=raw'))return new Response(JSON.stringify({raw:Buffer.from(`From: ${supplier.email}\r\nSubject: Invoice test\r\nMessage-ID: <${prefix}@test>\r\nContent-Type: text/plain\r\n\r\nInvoice No: MAIL-${prefix}\nRAM 1 150.00 150.00`).toString('base64url')}));return new Response(JSON.stringify({messages:[{id:'mock-message'}]}));};
      try{const callback=await app.inject({url:'/api/mailbox/callback?state='+u.searchParams.get('state')+'&code=test-code',headers:{cookie:oauthCookie}});assert.equal(callback.statusCode,302);const result=await call('/mailbox/sync',{});assert.equal(result.imported,1);assert.equal(result.errors.length,0);const retry=await call('/mailbox/sync',{});assert.equal(retry.duplicates,1);const replay=await app.inject({url:'/api/mailbox/callback?state='+u.searchParams.get('state')+'&code=test-code',headers:{cookie:oauthCookie}});assert.equal(replay.statusCode,400);}finally{globalThis.fetch=original;}
    });
    await t.test('saved email text and unsupported layouts remain reviewable without invented quantities',async()=>{const d=await extractDocument(Buffer.from('From: supplier@example.com\r\nSubject: Invoice\r\nContent-Type: text/plain\r\n\r\nInvoice No: ABC123\nUnusual layout'),'invoice.eml');assert.equal(d.sender,'supplier@example.com');assert.equal(d.parsed.lines.length,0);assert.ok(d.parsed.warnings.some(s=>s.includes('No reliable')));assert.equal(extractText('Some random text').total,null);});
    await t.test('text PDFs produce reviewable rows without losing the original PDF',async()=>{
      const stream='BT /F1 12 Tf 50 750 Td (Invoice No: PDF123) Tj 0 -20 Td (Invoice date: 05/09/2026) Tj 0 -20 Td (RAM kit 2 150.00 300.00) Tj ET';
      const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];
      let pdf='%PDF-1.4\n';const offsets=[0];for(const [i,o]of objects.entries()){offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;}const xref=Buffer.byteLength(pdf);pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
      const d=await extractDocument(Buffer.from(pdf),'invoice.pdf');assert.equal(d.parsed.invoiceNumber,'PDF123');assert.equal(d.parsed.lines[0].quantity,2);assert.equal(d.parsed.lines[0].lineTotal,300);assert.equal(d.contentType,'application/pdf');
    });
    await t.test('viewers can inspect matches but cannot modify connections or approve invoices',async()=>{const viewer=await db.user.create({data:{email:prefix+'viewer@test.invalid',name:'Viewer',role:'VIEWER',passwordHash:hashPassword(password)}});const r=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:viewer.email,password}});cookie=String(r.headers['set-cookie']).split(';')[0];await call('/matching');await call('/matching/shopify/'+mapping.id,{skuId:a.id},403,'PATCH');await call('/mailbox/status',undefined,403);await call('/invoices/'+invoice.id+'/approve',{version:invoice.version},403);});
  }finally{await app.close();await db.$disconnect();}
});
