import React, { useEffect, useState } from 'react';
import { api, date, money } from './api';
import { Modal } from './components';
import { originalMoney } from './fx-ui';

export function BankingPanel({ admin }: { admin: boolean }) {
  const [until, setUntil] = useState(new Date().toISOString().slice(0, 10));
  const [s, setS] = useState<any>(), [rows, setRows] = useState<any>({ rows: [], total: 0 }), [selected, setSelected] = useState<string[]>([]), [auto, setAuto] = useState(false);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [offset, setOffset] = useState(0), [account, setAccount] = useState(''), [search, setSearch] = useState('');
  const [appId, setAppId] = useState(''), [secret, setSecret] = useState(''), [mode, setMode] = useState('SANDBOX'), [since, setSince] = useState(new Date().toISOString().slice(0, 10)), [payment, setPayment] = useState<any>(), [purge, setPurge] = useState(false);
  async function load(reset = false, page = offset) {
    const [status, transactions] = await Promise.all([api('/banking/status'), api('/banking/transactions?' + new URLSearchParams({ offset: String(page), ...(account ? { accountId: account } : {}), ...(search ? { search } : {}) }))]);
    setS(status); setRows(transactions);
    if (reset) { setSelected(status.accounts.filter((a: any) => a.selected).map((a: any) => a.id)); setAuto(status.autoSync); setMode(status.mode); setSince(status.since.slice(0, 10)); }
  }
  useEffect(() => { if (admin) load(true).catch(e => setError(e.message)); }, [admin]);
  async function run(path: string, body: any = {}) {
    setBusy(true); setError(''); setNotice('');
    try { const result = await api('/banking/' + path, body); setNotice(result.message ?? 'Saved.'); await load(true); return result; }
    catch (e) { setError((e as Error).message); return null; } finally { setBusy(false); }
  }
  if (!admin) return <section className="panel"><h2>Banking</h2><p>Bank accounts and reconciliation are available to administrators.</p></section>;
  return <>
    <section className="panel"><h2>Akahu read-only bank feeds</h2><p>Godmode Ops uses Akahu to read connected BNZ account information and transactions for supplier invoice reconciliation. Access is ongoing until you revoke it. This integration cannot initiate payments.</p><p>Only selected eligible accounts are imported. Pending entries are a separate preview and cannot record payments. Confirm every invoice allocation yourself.</p><p><a href="https://www.akahu.nz/" target="_blank" rel="noreferrer">About Akahu</a> · Bank data stays in this ERP. Reconciliation evidence is retained for accounting review after disconnecting; you can remove unused transactions when disconnecting.</p>
      {s && <><strong>{s.status}</strong><p>Mode: {s.mode} · Full-app commercial gate: {s.commercialApproved ? 'Enabled by server administrator' : 'Not enabled'}</p><p>Callback to register: <code>{s.callbackUrl}</code></p><p>Last successful cached import: {s.lastSyncAt ? date(s.lastSyncAt) : 'Never'} · Last bank refresh request: {s.lastRefreshAttempt ? date(s.lastRefreshAttempt) : 'Never'}</p>{s.nextRequestAt && <p>Next request allowed: {date(s.nextRequestAt)}</p>}{s.error && <p className="error">{s.error}</p>}</>}
      {s?.personalTestEnabled && <div className="line-card"><h2>ISOLATED PERSONAL-APP TEST</h2><p>Separate test database. No Gmail or Shopify connection. One BNZ account, at most seven completed days, cached reads only. Scheduling and bank refresh are disabled. Allocations here are test records only.</p><div className="fields"><label>Personal App ID Token<input type="password" autoComplete="new-password" value={appId} onChange={e => setAppId(e.target.value)} /></label><label>User Access Token<input type="password" autoComplete="new-password" value={secret} onChange={e => setSecret(e.target.value)} /></label><label>Start date (UTC, inclusive)<input type="date" value={since} onChange={e => setSince(e.target.value)} /></label><label>End date (UTC, exclusive)<input type="date" value={until} onChange={e => setUntil(e.target.value)} /></label></div><button type="button" disabled={busy || s.status === 'CONNECTED'} onClick={async () => { const body = { appId, userToken: secret, since: since + 'T00:00:00.000Z', until: until + 'T00:00:00.000Z' }; setSecret(''); setAppId(''); await run('personal-test', body); }}>Save personal-test tokens securely</button><p>No OAuth callback is needed. Disconnect deletes local tokens; revoke the personal app yourself in Akahu if desired.</p></div>}
      {!s?.personalTestEnabled && <><p>Production requires Akahu full-app approval and server configuration. Sandbox credentials work only with an isolated test database.</p>
      <details><summary>Full-app connection settings</summary><div className="fields"><label>App ID Token<input autoComplete="off" value={appId} onChange={e => setAppId(e.target.value)} placeholder={s?.configured ? 'Leave blank to retain' : 'app_token_…'} /></label><label>App Secret<input type="password" autoComplete="new-password" value={secret} onChange={e => setSecret(e.target.value)} placeholder={s?.configured ? 'Leave blank to retain' : 'Full-app secret'} /></label><label>Environment<select value={mode} onChange={e => setMode(e.target.value)}><option value="SANDBOX">Sandbox — isolated database only</option><option value="PRODUCTION">Approved production full app</option></select></label><label>Import history from (UTC)<input type="date" value={since} onChange={e => setSince(e.target.value)} /></label></div><button type="button" disabled={busy} onClick={async () => { if (await run('configure', { ...(appId ? { appId } : {}), ...(secret ? { appSecret: secret } : {}), mode, since })) { setSecret(''); setAppId(''); } }}>Save encrypted settings</button></details>
      <div className="row"><button type="button" disabled={busy || !s?.configured || s?.status === 'CONNECTED'} onClick={async () => { const result = await run('authorize'); if (result?.url) window.location.assign(result.url); }}>Connect full app</button><button type="button" disabled={busy} onClick={() => load(true).catch(e => setError(e.message))}>Refresh banking view</button></div>
      </>}{error && <p className="error">{error}</p>}{notice && <p>{notice}</p>}
    </section>
    <section className="panel"><h2>BNZ accounts</h2><button type="button" disabled={busy || s?.status !== 'CONNECTED'} onClick={() => run('accounts/discover')}>Load connected accounts</button>
      {s?.accounts.map((a: any) => <div className="line-card" key={a.id}><label className="check"><input type="checkbox" disabled={!a.eligible || busy} checked={selected.includes(a.id)} onChange={e => setSelected(e.target.checked ? [...selected, a.id] : selected.filter(id => id !== a.id))} />{a.name} · {a.maskedNumber} · {a.currency}</label><p>{a.status} · Bank data refreshed: {a.refreshedAt ? date(a.refreshedAt) : 'Not known'}</p>{!a.eligible && <p>Not eligible for transaction imports. Reconnect inactive accounts or check transaction-read permissions/currency.</p>}{a.predecessorId && <p>This account replaced {a.predecessorId}. Review any earlier account history before selecting overlapping dates.</p>}</div>)}
      <label className="check"><input type="checkbox" disabled={s?.personalTestEnabled} checked={auto} onChange={e => setAuto(e.target.checked)} />Fetch cached transactions every 15 minutes while the ERP runs</label><button type="button" disabled={busy || s?.status !== 'CONNECTED'} onClick={() => run('accounts/select', { ids: selected, autoSync: auto })}>Save account selection</button>
      <div className="row"><button type="button" disabled={busy || s?.status !== 'CONNECTED'} onClick={() => run('sync')}>Fetch cached transactions / resume</button><button type="button" disabled={busy || s?.personalTestEnabled || s?.status !== 'CONNECTED'} onClick={() => run('refresh-bank')}>Request bank refresh</button><button type="button" disabled={busy || !['RUNNING', 'FAILED'].includes(s?.sync?.status)} onClick={() => run('sync/cancel')}>Cancel unfinished import</button></div>
      <p>{s?.personalTestEnabled ? 'Only cached data is fetched. Personal apps have a one-hour manual refresh rest period; this test does not request bank refreshes. Click Fetch again to resume a paginated import.' : 'Fetching cached data does not contact the bank for a new refresh. Manual refresh requests have a minimum 15-minute cooldown and may be deferred by Akahu. Refreshes can include other accounts sharing the same bank login.'}</p>
      {s?.sync && <p>Import {s.sync.status}: {s.sync.pages} pages saved, {s.sync.imported} provider rows processed. {s.sync.error} Refresh this view to see background progress.</p>}
    </section>
    <section className="panel"><h2>Posted bank transactions</h2><div className="fields"><label>Account<select value={account} onChange={e => setAccount(e.target.value)}><option value="">All imported accounts</option>{s?.accounts.map((a: any) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Description<input value={search} onChange={e => setSearch(e.target.value)} /></label></div><button type="button" onClick={() => { setOffset(0); load(false, 0).catch(e => setError(e.message)); }}>Apply filters</button>
      <table><thead><tr><th>Date / provider ID</th><th>Account</th><th>Description / references</th><th>Original bank amount</th><th>Unallocated NZD</th><th>Review</th></tr></thead><tbody>{rows.rows.map((t: any) => <tr key={t.id}><td>{date(t.date)}<small>{t.id}</small></td><td>{t.account.name}</td><td>{t.description}<small>{[t.references.particulars, t.references.code, t.references.reference, t.references.merchant].filter(Boolean).join(' · ')}</small></td><td>{originalMoney(t.amount, t.currency)}</td><td>{t.unallocatedNzd == null ? 'Not an NZD debit' : money(t.unallocatedNzd)}</td><td>{t.status}{t.reviewRequired && <strong> — changed after reconciliation</strong>}<button type="button" onClick={() => setPayment(t)}>Review / reconcile</button></td></tr>)}</tbody></table>
      <div className="row"><button type="button" disabled={offset === 0} onClick={() => { const n = Math.max(0, offset - 50); setOffset(n); load(false, n).catch(e => setError(e.message)); }}>Previous</button><span>{rows.total} transactions · page {Math.floor(offset / 50) + 1}</span><button type="button" disabled={offset + 50 >= rows.total} onClick={() => { const n = offset + 50; setOffset(n); load(false, n).catch(e => setError(e.message)); }}>Next</button></div>
    </section>
    <section className="panel"><h2>Pending preview — not available for reconciliation</h2>{s?.accounts.filter((a: any) => a.selected).map((a: any) => <div key={a.id}><h3>{a.name}</h3><p>Snapshot: {a.pendingAt ? date(a.pendingAt) : 'Not fetched'}</p>{a.pending.map((t: any, i: number) => <p key={i}>{date(t.date)} · {t.description} · {originalMoney(t.amount, t.currency)}</p>)}</div>)}<p>This preview is replaced after each completed account import. Only posted provider IDs can record payments.</p></section>
    <section className="panel"><h2>{s?.personalTestEnabled ? 'Disconnect personal test locally' : 'Disconnect and revoke access'}</h2><label className="check"><input type="checkbox" checked={purge} onChange={e => setPurge(e.target.checked)} />Also remove imported transactions that have never been allocated. Keep reconciliation and reversal evidence.</label><button type="button" disabled={busy || !s?.configured} onClick={() => run('disconnect', { purgeUnallocated: purge })}>{s?.personalTestEnabled ? 'Disconnect locally and delete saved tokens' : 'Disconnect and revoke Akahu access'}</button></section>
    {payment && <BankMatch payment={payment} close={() => setPayment(null)} saved={async () => { setPayment(null); await load(); }} />}
  </>;
}
function BankMatch({ payment: p, close, saved }: any) {
  const [matches, setMatches] = useState<any>({ suggestions: [] }), [invoices, setInvoices] = useState<any[]>([]), [invoiceId, setInvoiceId] = useState(''), [lines, setLines] = useState<any[]>([]), [note, setNote] = useState(''), [confirm, setConfirm] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false), [reason, setReason] = useState('');
  useEffect(() => { Promise.all([api('/banking/transactions/' + p.id + '/suggestions'), api('/banking/invoices')]).then(([m, i]) => { setMatches(m); setInvoices(i); }).catch(e => setError(e.message)); }, [p.id]);
  const add = (id: string) => { const i = invoices.find(x => x.id === id); if (!i || lines.some(l => l.invoiceId === id)) return; const remaining = i.total == null ? '' : Math.max(0, Number(i.total) - i.bankAllocations.reduce((n: number, a: any) => n + Number(a.originalAmount), 0)).toFixed(2); setLines([...lines, { invoiceId: id, invoiceVersion: i.version, originalAmount: remaining, amountNzd: '', feeNzd: '0', invoice: i }]); setConfirm(false); };
  const update = (index: number, key: string, value: string) => { setLines(lines.map((l, i) => i === index ? { ...l, [key]: value } : l)); setConfirm(false); };
  async function action(path: string, body: any) { setBusy(true); setError(''); try { await api(path, body); await saved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title="Review bank payment allocation" close={close}><p>{p.description} · {date(p.date)} · {originalMoney(p.amount, p.currency)} · available {money(p.unallocatedNzd)}</p><pre>{JSON.stringify(p.references, null, 2)}</pre><p>No invoice will be approved, no payment initiated and no stock received. Fees and exchange differences do not change approved stock costs.</p>
    <h3>Suggested invoices</h3>{matches.ambiguous && <p className="error">Ambiguous suggestions: more than one invoice has similar evidence. Verify the source before allocating.</p>}{matches.suggestions.map((m: any) => <div className="line-card" key={m.invoiceId}><strong>{m.invoiceNumber} · {m.supplier} · {m.currency} {m.remainingOriginal ?? 'unknown amount'} outstanding</strong><ul>{m.evidence.map((e: string) => <li key={e}>{e}</li>)}</ul><button type="button" onClick={() => add(m.invoiceId)}>Add to allocation review</button></div>)}
    <label>Choose another invoice<select value={invoiceId} onChange={e => setInvoiceId(e.target.value)}><option value="">Choose…</option>{invoices.map(i => <option key={i.id} value={i.id}>{i.invoiceNumber} · {i.supplier?.name} · {i.currency} {i.total ?? 'unknown'}</option>)}</select></label><button type="button" onClick={() => add(invoiceId)}>Add invoice</button>
    {lines.map((l, index) => <div className="line-card" key={l.invoiceId}><strong>{l.invoice.invoiceNumber}</strong><div className="fields"><label>Original principal paid ({l.invoice.currency})<input type="number" step="0.01" min="0" value={l.originalAmount} onChange={e => update(index, 'originalAmount', e.target.value)} /></label><label>Actual NZD principal<input type="number" step="0.01" min="0" value={l.amountNzd} onChange={e => update(index, 'amountNzd', e.target.value)} /></label><label>Fee included in this debit (NZD)<input type="number" step="0.01" min="0" value={l.feeNzd} onChange={e => update(index, 'feeNzd', e.target.value)} /></label></div><button type="button" onClick={() => { setLines(lines.filter((_, i) => i !== index)); setConfirm(false); }}>Remove row</button>{l.invoice.payments.filter((x: any) => !x.bankAllocationId && !x.reversedAt).map((x: any) => <p key={x.id}>Existing manual payment: {money(x.amountNzd)} · {x.reference}<button type="button" disabled={busy || reason.length < 5} onClick={() => action('/banking/manual-payments/' + x.id + '/reverse', { reason })}>Reverse duplicate manual payment</button></p>)}</div>)}
    <p>Total allocated NZD including fees: {money(lines.reduce((n, l) => n + Number(l.amountNzd || 0) + Number(l.feeNzd || 0), 0))}. Only include fees contained in this specific bank debit; a separate fee transaction must not be counted twice.</p><label>Evidence / explanation<input value={note} onChange={e => { setNote(e.target.value); setConfirm(false); }} /></label><label className="check"><input type="checkbox" checked={confirm} onChange={e => setConfirm(e.target.checked)} />I verified the invoice identities, original principal, actual NZD amounts and fees against the bank record.</label><button type="button" disabled={busy || !confirm || !lines.length || note.length < 3 || p.status !== 'POSTED' || p.reviewRequired || p.currency !== 'NZD'} onClick={() => action('/banking/transactions/' + p.id + '/allocate', { revision: p.revision, confirmed: true, note, lines: lines.map(({ invoice, ...l }) => l) })}>Confirm payment allocations</button>
    <h3>Allocation history</h3>{p.allocations.map((a: any) => <div className="line-card" key={a.id}><p>{a.invoice.invoiceNumber} · original {originalMoney(a.originalAmount, a.invoiceCurrency)} · actual NZD principal {money(a.amountNzd)} · fee {money(a.feeNzd)} · exchange difference {a.exchangeDifferenceNzd == null ? 'Unknown — no approved rate at allocation' : money(a.exchangeDifferenceNzd)}</p><p>{a.reversedAt ? 'Reversed: ' + a.reversalReason : 'Confirmed by ' + a.confirmedBy}</p>{!a.reversedAt && <button type="button" disabled={busy || reason.length < 5} onClick={() => action('/banking/allocations/' + a.id + '/reverse', { reason })}>Reverse allocation</button>}</div>)}<label>Reason for reversal<input value={reason} onChange={e => setReason(e.target.value)} placeholder="Explain an incorrect or duplicate match" /></label>{error && <p className="error">{error}</p>}
  </Modal>;
}
