import {useEffect,useState} from 'react';
import {api} from './api';
import {Modal} from './components';
const link=(v:any)=>`https://admin.shopify.com/store/${v.shopDomain.replace('.myshopify.com','')}/products/${v.productId.split('/').pop()}/variants/${v.variantId.split('/').pop()}`;
export function ComponentReview({admin}: {admin:boolean}){
 const [data,setData]=useState<any>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('priority'),[current,setCurrent]=useState<any>(),[sku,setSku]=useState(''),[variant,setVariant]=useState(''),[note,setNote]=useState(''),[alias,setAlias]=useState(false),[replace,setReplace]=useState(''),[product,setProduct]=useState(''),[variantSearch,setVariantSearch]=useState(''),[newCode,setNewCode]=useState(''),[newName,setNewName]=useState(''),[family,setFamily]=useState('');
 const load=async()=>setData(await api('/matching/review'));useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function run(path:string,body:any,method='POST'){setBusy(true);setError('');try{const result=await api('/matching/review/'+path,body,method);setNotice(result.ignored?`${result.added} candidates staged. Quantities and costs ignored.`:result.applied!=null?`${result.applied} draft lines mapped; ${result.skipped} left for review.`:'Saved');await load();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 if(!data)return <p>{error||'Loading component review…'}</p>;
 const items=data.items.filter((r:any)=>(filter==='all'||filter==='unresolved'&&!r.confirmed||filter==='priority'&&(r.lineId||r.counted)||filter==='counted'&&r.counted)&&JSON.stringify([r.code,r.description,r.invoiceNumber,r.supplier,r.candidates.map((c:any)=>[c.code,c.name])]).toLowerCase().includes(search.toLowerCase()));
 const selected=data.skus.find((s:any)=>s.id===sku);
 const variants=data.variants.filter((v:any)=>!v.finished&&(v.skuId===sku||v.shopifySku&&v.shopifySku.toUpperCase()===selected?.code.toUpperCase()||variantSearch&&(`${v.productTitle} ${v.variantTitle} ${v.shopifySku}`).toLowerCase().includes(variantSearch.toLowerCase())));
 return <section className="panel"><h2>Component matching review</h2><p>Catalogue candidates only. Stocktake quantities and costs are ignored. Confirmations update draft mappings, never invoice approval or stock.</p><p>{data.progress.confirmed} / {data.progress.total} confirmed · {data.progress.unresolved} unresolved · {data.progress.counted} marked counted</p>
 {admin&&<label>Stage stocktake CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>8*1024*1024){setError('Maximum file size is 8 MB');return;}await run('import',{csv:await file.text()});e.target.value='';}} /></label>}
 <div className="fields"><label>Search descriptions, codes or invoice numbers<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Review queue<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="priority">Invoice components and counted products</option><option value="unresolved">All unresolved</option><option value="counted">Marked counted</option><option value="all">All candidates and draft lines</option></select></label></div>
 <button disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh review</button>{admin&&<button disabled={busy} onClick={()=>run('apply-aliases',{})}>Apply confirmed code aliases to eligible drafts</button>}
 {error&&<p className="error">{error}</p>}{notice&&<p>{notice}</p>}
 <div style={{overflowX:'auto'}}><table><thead><tr><th>Spreadsheet SKU / description</th><th>Supplier / invoice line</th><th>Proposed ERP component</th><th>Exact Shopify variant</th><th>Evidence / conflicts</th><th>Review</th></tr></thead><tbody>{items.map((r:any)=>{const candidate=r.suggestion.candidates.find((s:any)=>s.skuId===r.skuId)??r.suggestion.candidates[0];const erp=data.skus.find((s:any)=>s.id===r.skuId)??candidate?.sku;return <tr key={r.id}><td>{r.candidates.length?r.candidates.map((c:any)=><div key={c.id}><strong>{c.code||'Missing SKU'}</strong><div>{c.name||'Missing name'}</div>{c.flags.map((f:string)=><small className="error" key={f}>{f}</small>)}</div>):'No exact spreadsheet association'}</td><td>{r.lineId?<>{r.supplier||'Supplier unresolved'} · {r.invoiceNumber}<div>{r.code||'No supplier code'} · {r.description}</div></>:'Catalogue candidate'}</td><td>{erp?`${erp.code} · ${erp.name}`:'Choose existing component'}<div>{r.confirmed?'Confirmed':'Suggestion only'}</div></td><td>{(candidate?.shopify??[]).map((v:any)=><div key={v.id}><a href={link(v)} target="_blank" rel="noreferrer">{v.productTitle} · {v.variantTitle}</a></div>)}{!candidate?.shopify?.length&&'No confirmed Shopify link required'}</td><td>{r.suggestion.reason}{candidate?.conflicts?.map((c:string)=><div className="error" key={c}>{c}</div>)}</td><td>{admin&&<><button onClick={()=>{setCurrent(r);setSku(r.skuId??r.suggestion.suggestedSkuId??'');setVariant('');setNote('');setAlias(false);setReplace('');setNewCode(r.code??'');setNewName(r.description??'');setFamily('');}}>Confirm / correct</button>{r.candidateId&&<label><input type="checkbox" checked={r.counted} onChange={e=>run('counted',{id:r.candidateId,version:r.candidateVersion,counted:e.target.checked},'PATCH')}/>Counted — priority only</label>}</>}</td></tr>;})}</tbody></table></div>
 {current&&<Modal title="Review component identity" close={()=>setCurrent(null)}><p>{current.supplier} · {current.code} · {current.description}</p><label>ERP component<select value={sku} onChange={e=>setSku(e.target.value)}><option value="">Select a component</option>{data.skus.map((s:any)=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><details><summary>Create a reviewed component if none exists</summary><p>Creates a catalogue identity only. No stock, costs or invoice confirmation.</p><label>Unique ERP SKU<input value={newCode} onChange={e=>setNewCode(e.target.value)}/></label><label>Verified component description<input value={newName} onChange={e=>setNewName(e.target.value)}/></label><label>Family<select value={family} onChange={e=>setFamily(e.target.value)}><option value="">Select</option>{data.families.map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button disabled={busy||!newCode||!newName||!family} onClick={async()=>{if(await run('create-component',{code:newCode,name:newName,familyId:family,confirmed:true}))setNotice('Component created. Select it above and review the mapping.');}}>Create reviewed catalogue component</button></details><label>Search Shopify variants<input value={variantSearch} onChange={e=>setVariantSearch(e.target.value)}/></label><label>Shopify exact variant (optional)<select value={variant} onChange={e=>setVariant(e.target.value)}><option value="">No Shopify link / retain existing links</option>{variants.map((v:any)=><option key={v.id} value={v.id}>{v.productTitle} · {v.variantTitle} · {v.shopifySku}</option>)}</select></label><p>Use the queue search to narrow Shopify variants. Model, colour, capacity and pack size must agree. A unit-versus-kit mapping does not convert invoice quantities.</p><label>Evidence and resolution of conflicts<textarea value={note} onChange={e=>setNote(e.target.value)}/></label>{current.lineId&&<><label><input type="checkbox" checked={alias} onChange={e=>setAlias(e.target.checked)}/>Save this supplier code as an alias</label><label>Previous component, only when correcting a conflicting alias<select value={replace} onChange={e=>setReplace(e.target.value)}><option value="">No conflicting alias</option>{data.skus.map((s:any)=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label></>}<button disabled={busy||!sku} onClick={async()=>{if(await run('confirm',{...(current.lineId?{lineId:current.lineId}:{candidateId:current.candidateId}),version:current.invoiceVersion??current.candidateVersion,skuId:sku,...(variant?{variantId:variant}:{}),rememberAlias:alias,...(replace?{replaceAliasSkuId:replace}:{}),note}))setCurrent(null);}}>Confirm reviewed mapping</button></Modal>}
 <details><summary>Finished Shopify PCs → BOMs</summary><p>These variants select a complete build product, never one component.</p><label>Exact finished-PC variant<select value={variant} onChange={e=>setVariant(e.target.value)}><option value="">Select</option>{data.variants.filter((v:any)=>v.finished).map((v:any)=><option key={v.id} value={v.id}>{v.productTitle} · {v.variantTitle}</option>)}</select></label><label>Product with active BOM<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Select</option>{data.products.filter((p:any)=>p.bomVersions.some((b:any)=>b.lines.length)).map((p:any)=><option key={p.id} value={p.id}>{p.name} · active BOM</option>)}</select></label>{admin&&<button disabled={busy||!variant||!product} onClick={()=>run('build-link',{variantId:variant,productId:product})}>Confirm variant → BOM product</button>}</details></section>;
}
