import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { label } from './api';
export const Badge = ({ value }: { value: string }) => <span className={'badge b-' + value?.toLowerCase()}>{label(value)}</span>;
export type Field = { name: string; label: string; type?: string; value?: any; required?: boolean; options?: { id: string; name: string }[]; min?: number; hint?: string; step?: string };
export function Fields({ fields }: { fields: Field[] }) { return <div className="fields">{fields.map(f => <label key={f.name}>{f.label}{f.type === 'textarea' ? <textarea name={f.name} defaultValue={f.value} required={f.required !== false} rows={4} /> : f.options ? <select name={f.name} defaultValue={f.value ?? ''} required={f.required !== false}><option value="">Choose…</option>{f.options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select> : <input name={f.name} type={f.type ?? 'text'} defaultValue={f.value} required={f.required !== false} min={f.min} step={f.step ?? (f.type === 'number' ? 'any' : undefined)} autoComplete={f.type === 'password' ? 'new-password' : undefined} />}{f.hint && <small>{f.hint}</small>}</label>)}</div>; }
export function Modal({ title, children, close, submit, action = 'Save', description }: { title: string; children: ReactNode; close: () => void; submit?: (data: FormData) => Promise<void>; action?: string; description?: string }) {
  const ref = useRef<HTMLDialogElement>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { ref.current?.showModal(); return () => ref.current?.close(); }, []);
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!submit || busy) return; setBusy(true); setError(''); try { await submit(new FormData(e.currentTarget)); close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <dialog ref={ref} onCancel={e => { if (busy) e.preventDefault(); else close(); }}><div className="modal-head"><h2>{title}</h2><button type="button" aria-label="Close dialog" disabled={busy} onClick={close}>×</button></div>{description && <p className="muted">{description}</p>}<form onSubmit={save}>{children}{error && <p className="error" role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={close}>Close</button>{submit && <button className="primary" disabled={busy}>{busy ? 'Saving…' : action}</button>}</footer></form></dialog>;
}
export type Column = { key: string; label: string; render?: (r: any) => ReactNode; sort?: (r: any) => string | number };
export function Table({ rows, columns, empty = 'No records yet.', searchable = true }: { rows: any[]; columns: Column[]; empty?: string; searchable?: boolean }) {
  const [search, setSearch] = useState(''), [sort, setSort] = useState(''), [asc, setAsc] = useState(true), [page, setPage] = useState(0);
  const column = columns.find(c => c.key === sort);
  const filtered = rows.filter(r => JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).sort((a, b) => { if (!column) return 0; const av = column.sort ? column.sort(a) : a[column.key], bv = column.sort ? column.sort(b) : b[column.key]; return (typeof av === 'number' && typeof bv === 'number' ? av - bv : String(av ?? '').localeCompare(String(bv ?? ''), 'en', { numeric: true })) * (asc ? 1 : -1); });
  const currentPage = Math.min(page, Math.max(0, Math.ceil(filtered.length / 30) - 1));
  return <section className="table-wrap">{searchable && <div className="table-tools"><input aria-label="Search records" placeholder="Search records…" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /><span>{filtered.length} records</span></div>}<div className="table-scroll"><table><thead><tr>{columns.map(c => <th key={c.key}><button onClick={() => { setSort(c.key); setAsc(sort === c.key ? !asc : true); }}>{c.label}{sort === c.key ? asc ? ' ↑' : ' ↓' : ''}</button></th>)}</tr></thead><tbody>{filtered.slice(currentPage * 30, currentPage * 30 + 30).map((r, i) => <tr key={r.id ?? `${r.skuId}-${r.locationId}-${i}`}>{columns.map(c => <td key={c.key}>{c.render ? c.render(r) : r[c.key] ?? '—'}</td>)}</tr>)}</tbody></table>{!filtered.length && <div className="empty">{empty}</div>}</div>{filtered.length > 30 && <div className="pagination"><button disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Previous</button><span>Page {currentPage + 1} of {Math.ceil(filtered.length / 30)}</span><button disabled={(currentPage + 1) * 30 >= filtered.length} onClick={() => setPage(currentPage + 1)}>Next</button></div>}</section>;
}
export function LineEditor({ skus, kind = 'bom', initial }: { skus: any[]; kind?: 'bom' | 'po' | 'order'; initial?: any[] }) {
  const blank = () => kind === 'bom' ? { role: '', quantity: 1, exactSkuId: '', approvedSkuIds: [] } : kind === 'po' ? { skuId: '', quantityOrdered: 1, unitCost: 0 } : { productId: '', quantity: 1 };
  const [lines, setLines] = useState<any[]>(initial ?? [blank()]);
  const change = (i: number, key: string, value: any) => setLines(lines.map((l, j) => j === i ? { ...l, [key]: value } : l));
  return <div className="line-editor"><input type="hidden" name="lines" value={JSON.stringify(lines)} />{lines.map((l, i) => <div className="line-card" key={i}><div className="row between"><strong>Line {i + 1}</strong><button type="button" disabled={lines.length === 1} onClick={() => setLines(lines.filter((_, j) => i !== j))}>Remove</button></div><div className="fields">{kind === 'bom' && <label>Role<input aria-label={`Role ${i + 1}`} value={l.role} required onChange={e => change(i, 'role', e.target.value.toUpperCase())} placeholder="CPU, GPU, RAM…" /></label>}<label>{kind === 'order' ? 'Product' : 'Component'}<select required value={l[kind === 'bom' ? 'exactSkuId' : kind === 'po' ? 'skuId' : 'productId']} onChange={e => change(i, kind === 'bom' ? 'exactSkuId' : kind === 'po' ? 'skuId' : 'productId', e.target.value)}><option value="">Choose…</option>{skus.map(s => <option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><label>Quantity<input type="number" min="1" step="1" required value={l[kind === 'po' ? 'quantityOrdered' : 'quantity']} onChange={e => change(i, kind === 'po' ? 'quantityOrdered' : 'quantity', Number(e.target.value))} /></label>{kind === 'po' && <label>Unit cost, ex GST<input type="number" min="0" step="0.01" required value={l.unitCost} onChange={e => change(i, 'unitCost', Number(e.target.value))} /></label>}{kind === 'bom' && <label>Approved alternatives<select multiple value={l.approvedSkuIds ?? []} onChange={e => change(i, 'approvedSkuIds', Array.from(e.target.selectedOptions).map(o => o.value))}>{skus.filter(s => s.id !== l.exactSkuId).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><small>Optional. Hold Ctrl to select multiple.</small></label>}</div></div>)}<button type="button" onClick={() => setLines([...lines, blank()])}>+ Add line</button></div>;
}
export const value = (f: FormData, key: string) => String(f.get(key) ?? '').trim();
export const number = (f: FormData, key: string) => Number(f.get(key));
export const serials = (f: FormData, key = 'serialNumbers') => value(f, key).split(/[\n,]/).map(x => x.trim()).filter(Boolean);
