import React,{useState,useEffect} from 'react';
import {api} from './api';
export const originalMoney=(value:any,currency='NZD',digits=2)=>value==null?'Not entered':! /^[A-Z]{3}$/.test(currency)?`${value} (choose currency)`:new Intl.NumberFormat('en-NZ',{style:'currency',currency,minimumFractionDigits:2,maximumFractionDigits:digits}).format(Number(value));
export function converted(value:any,r:any,saved?:any,digits=2){
 if(r.fxLockedAt)return saved==null?'Needs review':originalMoney(saved,'NZD',digits);
 if(value==null||(!r.fxRate&&r.currency!=='NZD'))return 'Rate / amount needed';
 return originalMoney(Number(value)*(r.currency==='NZD'?1:Number(r.fxRate)),'NZD',digits)+' (preview)';
}
export function FxPanel({record:r,kind='invoices',editable,reload,dirty=false}:any){
 const [rate,setRate]=useState(''),[effective,setEffective]=useState(''),[source,setSource]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{setRate(r.fxRate??'');setEffective(r.fxDate?.slice(0,10)??'');setSource(r.fxManual?r.fxSource?.replace(/^Manual override: /,'')??'':'');setConfirmed(false);},[r.version,r.id]);
 async function act(path:string,body:any,method='POST'){setBusy(true);setError('');try{await api(`/${kind}/${r.id}/fx${path}`,body,method);await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const date=(kind==='invoices'?r.invoiceDate:r.orderDate)?.slice(0,10);
 return <section className="panel fx-panel"><h3>Exchange rate to NZD</h3><strong>1 {r.currency} = {r.currency==='NZD'?'1':r.fxRate??'not set'} NZD</strong><p>Invoice/order date: {date??'not entered'} · Effective rate date: {r.fxDate?.slice(0,10)??'not entered'}</p><p>{r.fxSource??'No rate source recorded'}</p><p>{r.fxLockedAt?`Locked at approval/ordering: ${r.fxLockedAt}`:r.fxConfirmed&&!r.fxNeedsReview?'Rate confirmed':'Rate requires review and confirmation'}</p>{r.currency!=='NZD'&&editable&&!r.fxLockedAt&&<><p>Historical lookup uses Frankfurter / ECB daily reference rates. Weekends and holidays may return the preceding business day. A reference rate can differ from your bank’s actual payment rate.</p>{dirty&&<p>Save the draft before editing its exchange rate.</p>}<div className="row"><button type="button" disabled={busy||dirty||!date} onClick={()=>act('/lookup',{version:r.version})}>Look up invoice-date rate</button><button type="button" disabled={busy||dirty||!r.fxRate} onClick={()=>act('',{version:r.version,mode:'CONFIRM',confirmed:true},'PATCH')}>Confirm displayed rate</button></div><details><summary>Manual rate / override</summary><div className="fields"><label>1 {r.currency} equals this many NZD<input type="number" min="0.0000000001" step="0.0000000001" value={rate} onChange={e=>{setRate(e.target.value);setConfirmed(false);}}/></label><label>Rate effective date<input type="date" max={date} value={effective} onChange={e=>{setEffective(e.target.value);setConfirmed(false);}}/></label><label>Source and reason for override<input value={source} onChange={e=>{setSource(e.target.value);setConfirmed(false);}} placeholder="Bank / provider, rate date and reason"/></label></div><label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified the direction, effective date and source of this manual rate.</label><button type="button" disabled={busy||dirty||!rate||!effective||!source} onClick={()=>act('',{version:r.version,mode:'MANUAL',rate,effectiveDate:effective,source,confirmed},'PATCH')}>Save manual rate</button></details></>}{error&&<p className="error">{error}</p>}<table><thead><tr><th>Amount</th><th>Original {r.currency}</th><th>NZD {r.fxLockedAt?'locked':'preview'}</th></tr></thead><tbody><tr><td>Goods subtotal</td><td>{originalMoney(r.subtotal,r.currency)}</td><td>{converted(r.subtotal,r,r.nzd?.subtotalNzd)}</td></tr><tr><td>Invoice/order total</td><td>{originalMoney(r.total,r.currency)}</td><td>{converted(r.total,r,r.nzd?.totalNzd)}</td></tr></tbody></table>{r.nzd&&<p>Allocated stock value: {originalMoney(r.nzd.stockValueNzd)} NZD. Tax and expensed charges are excluded.</p>}{r.nzdPreviewError&&<p className="muted">Stock-cost preview: {r.nzdPreviewError}</p>}</section>;
}
export function ChargeAllocation({record:r,change,disabled,lineCount}:any){
 const names:any={freight:'Freight',importCharges:'Import charges',paymentFees:'Payment fees'};
 return <section className="panel"><h3>Charges and stock-cost allocation</h3><p>Amounts are in {r.currency}, excluding recoverable GST/tax. Choose explicitly which charges form part of stock value. A bank payment fee must not be counted again if already included here.</p>{Object.keys(names).map(k=>{const a=r.costAllocation?.[k]??{};return <div className="fields" key={k}><label>{names[k]} ({r.currency})<input disabled={disabled} type="number" min="0" step="0.01" value={r[k]??''} onChange={e=>change(k,e.target.value===''?null:Number(e.target.value))}/></label><label>{names[k]} allocation<select disabled={disabled} value={a.method??''} onChange={e=>change('costAllocation',{...r.costAllocation,[k]:{method:e.target.value,...(e.target.value==='MANUAL'?{amounts:Array(lineCount).fill(0)}:{})}})}><option value="">Choose treatment</option><option value="EXPENSE">Expense - exclude from stock</option><option value="VALUE">Include - allocate by goods value</option><option value="QUANTITY">Include - allocate by quantity</option><option value="MANUAL">Include - manual line allocation</option></select></label>{a.method==='MANUAL'&&<label>Amounts per line in {r.currency}, in line order (comma separated)<input disabled={disabled} value={(a.amounts??[]).join(',')} onChange={e=>change('costAllocation',{...r.costAllocation,[k]:{...a,amounts:e.target.value.split(',').map((s:string)=>Number(s.trim()))}})}/></label>}</div>;})}</section>;
}
export function Payments({record:r,writable,reload}:any){
 const [amount,setAmount]=useState(''),[paidAt,setDate]=useState(new Date().toISOString().slice(0,10)),[reference,setRef]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <section className="panel"><h3>Actual NZD payments</h3><p>Payments are separate from the approved invoice conversion and never change stock valuation.</p>{r.payments?.map((p:any)=><p key={p.id}>{p.paidAt.slice(0,10)} · {originalMoney(p.amountNzd)} · {p.reference}{p.reversedAt?' · REVERSED: '+p.reversalReason:''}{p.bankAllocationId?' · Bank reconciled (fees shown in Banking)':''}</p>)}<p>Recorded payments to date: {originalMoney((r.payments??[]).filter((p:any)=>!p.reversedAt).reduce((s:number,p:any)=>s+Number(p.amountNzd),0))}</p>{writable&&<details><summary>Record an actual payment</summary><div className="fields"><label>Amount actually paid (NZD)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Payment date<input type="date" value={paidAt} onChange={e=>setDate(e.target.value)}/></label><label>Bank/payment reference<input value={reference} onChange={e=>setRef(e.target.value)}/></label></div><button type="button" disabled={busy||!amount||!paidAt||!reference} onClick={async()=>{setError('');setBusy(true);try{await api(`/invoices/${r.id}/payments`,{amountNzd:Number(amount),paidAt,reference});setAmount('');setRef('');await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Record payment</button></details>}{error&&<p className="error">{error}</p>}</section>;
}
export function PoCostReview({po,writable,refresh}:any){
 const [r,setR]=useState(po),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false);
 const reload=async()=>{const list=await api('/purchase-orders');setR(list.find((p:any)=>p.id===po.id));setDirty(false);await refresh();};
 const editable=writable&&!r.fxLockedAt&&r.lines.every((l:any)=>l.quantityReceived===0);
 const change=(k:string,v:any)=>{setR({...r,[k]:v});setDirty(true);};
 return <><FxPanel record={r} kind="purchase-orders" editable={editable} reload={reload} dirty={dirty}/><ChargeAllocation record={r} change={change} disabled={!editable} lineCount={r.lines.length}/>{editable&&<><div className="fields"><label>Original currency<input value={r.currency} onChange={e=>change('currency',e.target.value.toUpperCase())}/></label><label>Order/rate date<input type="date" value={r.orderDate.slice(0,10)} onChange={e=>change('orderDate',e.target.value)}/></label><label>Tax (original currency)<input type="number" min="0" step="0.01" value={r.tax??''} onChange={e=>change('tax',Number(e.target.value))}/></label></div><button type="button" disabled={!dirty||busy} onClick={async()=>{setBusy(true);setError('');try{await api(`/purchase-orders/${r.id}/costing`,{version:r.version,currency:r.currency,orderDate:r.orderDate.slice(0,10),freight:r.freight,tax:r.tax,importCharges:r.importCharges,paymentFees:r.paymentFees,costAllocation:r.costAllocation},'PATCH');await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Save PO costing</button></>}{error&&<p className="error">{error}</p>}<table><thead><tr><th>Component</th><th>Original unit cost</th><th>NZD goods unit cost</th><th>NZD stock value</th></tr></thead><tbody>{r.lines.map((l:any,i:number)=><tr key={l.id}><td>{l.sku.name}</td><td>{originalMoney(l.unitCost,r.currency)}</td><td>{converted(l.unitCost,r,l.nzdUnitCost,8)}</td><td>{originalMoney(l.stockValueNzd??r.nzd?.lines?.[i]?.stockValueNzd)}</td></tr>)}</tbody></table></>;
}
