import { createHash } from 'node:crypto';
import { Prisma, type PrismaClient } from '@prisma/client';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { actor, ensure, json, mutate, type Tx } from './core.js';
import { extractDocument } from './invoice-extract.js';
import { matchContext, normalize, suggestMatch } from './matching.js';
const id=z.string().min(1).max(200), cash=z.number().finite().min(0).max(999999999).nullable();
const lineSchema=z.object({description:z.string().trim().min(1).max(2000),supplierCode:z.string().trim().max(200).nullable().optional(),barcode:z.string().trim().max(200).nullable().optional(),quantity:z.number().int().min(1).max(100000).nullable(),unitCost:cash,lineTotal:cash,skuId:id.nullable(),confirmed:z.boolean()});
const editSchema=z.object({version:z.number().int(),supplierId:id.nullable(),invoiceNumber:z.string().trim().max(100).nullable(),invoiceDate:z.string().nullable(),dueDate:z.string().nullable(),currency:z.string().regex(/^[A-Z]{3}$/),subtotal:cash,tax:cash,freight:cash,total:cash,purchaseOrderId:id.nullable(),lines:z.array(lineSchema).max(500)});
const include={lines:{orderBy:{position:'asc' as const},include:{sku:true}},supplier:true,purchaseOrder:{include:{lines:{include:{sku:true}}}},files:{select:{id:true,filename:true,contentType:true}}};
export async function ingestInvoice(tx:Tx,bytes:Buffer,filename:string,document:Awaited<ReturnType<typeof extractDocument>>,source='UPLOAD',sourceRef?:string) {
  const fingerprint=createHash('sha256').update(bytes).digest('hex'),old=await tx.supplierInvoice.findUnique({where:{fingerprint}});if(old)return {id:old.id,duplicate:true};
  const suppliers=document.sender?await tx.supplier.findMany({where:{active:true,email:{equals:document.sender,mode:'insensitive'}}}):[];
  const supplierId=suppliers.length===1?suppliers[0].id:null;const ctx=await matchContext(tx),p=document.parsed;
  const invoice=await tx.supplierInvoice.create({data:{fingerprint,source,sourceRef:sourceRef??document.sourceRef,sender:document.sender,subject:document.subject,supplierId,invoiceNumber:p.invoiceNumber,invoiceDate:p.invoiceDate,dueDate:p.dueDate,subtotal:p.subtotal,tax:p.tax,freight:p.freight,total:p.total,extractedText:document.text,extractionWarnings:json(p.warnings),files:{create:{filename:filename.replace(/[\r\n]/g,'').slice(0,200),contentType:document.contentType,data:new Uint8Array(bytes)}},lines:{create:p.lines.map((l,position)=>{const m=suggestMatch(ctx,l,supplierId);return {...l,position,skuId:m.suggestedSkuId,matchReason:m.reason,confirmed:false};})}}});return {id:invoice.id,duplicate:false};
}
export function invoiceIssues(invoice:any) {
  const issues:string[]=[];const cents=(x:any)=>new Prisma.Decimal(x??0).mul(100).round().toNumber();
  if(!invoice.supplierId)issues.push('Choose a supplier');if(!invoice.invoiceNumber)issues.push('Enter an invoice number');if(!invoice.invoiceDate)issues.push('Enter the invoice date');
  if(!invoice.lines.length)issues.push('Add at least one component line');
  for(const [i,l] of invoice.lines.entries()){if(!l.skuId||!l.confirmed)issues.push(`Line ${i+1}: confirm the ERP SKU`);if(!l.quantity||l.unitCost==null||l.lineTotal==null)issues.push(`Line ${i+1}: enter quantity, unit cost and total`);else if(Math.abs(cents(l.unitCost)*l.quantity-cents(l.lineTotal))>1)issues.push(`Line ${i+1}: quantity × unit cost does not match the line total`);}
  for(const k of ['subtotal','tax','freight','total'])if(invoice[k]==null)issues.push(`Enter ${k} (use 0 where applicable)`);
  if(invoice.subtotal!=null&&Math.abs(invoice.lines.reduce((n:number,l:any)=>n+cents(l.lineTotal),0)-cents(invoice.subtotal))>1)issues.push('Line totals do not match subtotal');
  if(invoice.total!=null&&Math.abs(cents(invoice.subtotal)+cents(invoice.tax)+cents(invoice.freight)-cents(invoice.total))>1)issues.push('Subtotal + GST/tax + freight does not match invoice total');
  return issues;
}
function poDifferences(invoice:any){const p=invoice.purchaseOrder;if(!p)return[];const diffs:string[]=[];if(p.supplierId!==invoice.supplierId||p.currency!==invoice.currency)diffs.push('Purchase order supplier or currency differs');for(const l of invoice.lines){const matches=p.lines.filter((x:any)=>x.skuId===l.skuId);if(matches.length!==1)diffs.push(`${l.description}: no unique matching PO line`);else {if(Number(matches[0].unitCost)!==Number(l.unitCost))diffs.push(`${l.description}: invoiced unit cost ${l.unitCost} vs PO ${matches[0].unitCost}`);if(l.quantity>matches[0].quantityOrdered)diffs.push(`${l.description}: invoice quantity exceeds the PO quantity`);}}return diffs;}
export async function registerInvoices(app:FastifyInstance,db:PrismaClient){
  app.get('/invoices',async()=>db.supplierInvoice.findMany({orderBy:{createdAt:'desc'},take:500,select:{id:true,invoiceNumber:true,invoiceDate:true,supplier:true,sender:true,subject:true,status:true,total:true,currency:true,createdAt:true,version:true,_count:{select:{lines:true}}}}));
  app.post('/invoices/upload',{bodyLimit:12*1024*1024},async q=>{const b=z.object({filename:z.string().min(1).max(200),base64:z.string().max(12*1024*1024)}).parse(q.body),bytes=Buffer.from(b.base64,'base64');const document=await extractDocument(bytes,b.filename);return mutate(db,q,'Import supplier invoice',tx=>ingestInvoice(tx,bytes,b.filename,document));});
  app.get('/invoices/:id',async q=>{const invoice=await db.supplierInvoice.findUniqueOrThrow({where:{id:(q.params as any).id},include});const ctx=await matchContext(db);return {...invoice,issues:invoiceIssues(invoice),poDifferences:poDifferences(invoice),lines:invoice.lines.map(l=>({...l,suggestion:suggestMatch(ctx,l,invoice.supplierId),shopify:ctx.variants.filter(v=>v.skuId===l.skuId&&v.confirmedAt)}))};});
  app.get('/invoices/:id/files/:fileId',async(q,r)=>{const {id,fileId}=q.params as any,file=await db.invoiceFile.findUniqueOrThrow({where:{id:fileId}});ensure(file.invoiceId===id,'File does not belong to this invoice',404);return r.header('content-disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.filename)}`).header('x-content-type-options','nosniff').header('cache-control','no-store').type(file.contentType).send(Buffer.from(file.data));});
  app.patch('/invoices/:id',async q=>{const b=editSchema.parse(q.body),{id:invoiceId}=q.params as any;return mutate(db,q,'Review invoice lines',async tx=>{
    const old=await tx.supplierInvoice.findUniqueOrThrow({where:{id:invoiceId}});ensure(old.status==='REVIEW','Approved invoices are permanent; import a supplier correction separately');ensure(old.version===b.version,'This invoice was changed in another window. Reopen it before editing.');
    if(b.supplierId)ensure((await tx.supplier.findUnique({where:{id:b.supplierId}}))?.active,'Choose an active supplier',400);
    if(b.purchaseOrderId){const p=await tx.purchaseOrder.findUniqueOrThrow({where:{id:b.purchaseOrderId}});ensure(p.supplierId===b.supplierId&&p.currency===b.currency&&p.status!=='CANCELLED','The PO must belong to this supplier and currency and not be cancelled',400);}
    const ctx=await matchContext(tx);const lines=b.lines.map((l,position)=>{if(l.skuId)ensure(ctx.skus.some(s=>s.id===l.skuId),'An invoice line references an inactive or missing SKU',400);const m=suggestMatch(ctx,l,b.supplierId);return {...l,position,confirmed:l.confirmed&&Boolean(l.skuId)&&old.supplierId===b.supplierId,matchReason:l.confirmed?'Manually confirmed while reviewing invoice':m.reason};});
    const dt=(s:string|null)=>{if(!s)return null;const d=new Date(s);ensure(Number.isFinite(d.getTime()),'Invalid invoice date',400);return d;};
    const {lines:_,version:__,...header}=b;await tx.supplierInvoiceLine.deleteMany({where:{invoiceId}});
    return tx.supplierInvoice.update({where:{id:invoiceId},data:{...header,invoiceDate:dt(b.invoiceDate),dueDate:dt(b.dueDate),version:{increment:1},lines:{create:lines}},include});
  });});
  app.post('/invoices/:id/approve',async q=>{const b=z.object({version:z.number().int(),rememberAliases:z.boolean().default(true),acceptPoDifferences:z.boolean().default(false)}).parse(q.body);return mutate(db,q,'Approve supplier invoice',async tx=>{
    const invoice=await tx.supplierInvoice.findUniqueOrThrow({where:{id:(q.params as any).id},include});ensure(invoice.status==='REVIEW'&&invoice.version===b.version,'Reopen the latest invoice before approving');const issues=invoiceIssues(invoice);ensure(!issues.length,issues.join('; '),400);ensure(!poDifferences(invoice).length||b.acceptPoDifferences,'Review and acknowledge purchase order differences',400);
    const invoiceKey=invoice.supplierId+'|'+normalize(invoice.invoiceNumber);ensure(!(await tx.supplierInvoice.findUnique({where:{invoiceKey}})),'This supplier invoice number was already approved');
    for(const l of invoice.lines){const sku=await tx.sku.findUniqueOrThrow({where:{id:l.skuId!}});ensure(sku.active,'Invoice contains an inactive SKU',400);const variants=await tx.shopifyCatalogVariant.findMany({where:{skuId:l.skuId,confirmedAt:{not:null}}});await tx.supplierInvoiceLine.update({where:{id:l.id},data:{matchSnapshot:json({sku:{id:sku.id,code:sku.code,name:sku.name},shopify:variants.map(v=>({shopDomain:v.shopDomain,variantId:v.variantId,productTitle:v.productTitle,variantTitle:v.variantTitle,shopifySku:v.shopifySku})),approvedBy:actor(q)})}});
      if(b.rememberAliases) for(const [kind,value] of [['NAME',l.description],['CODE',l.supplierCode]] as const)if(value){const where={supplierId_kind_key:{supplierId:invoice.supplierId!,kind,key:normalize(value)}};const previous=await tx.supplierAlias.findUnique({where});ensure(!previous||previous.skuId===l.skuId,`Alias "${value}" already maps to a different SKU. Correct it in SKU Matching or approve without remembering aliases.`,409);await tx.supplierAlias.upsert({where,create:{supplierId:invoice.supplierId!,skuId:l.skuId!,kind,key:normalize(value),value,confirmedBy:actor(q)},update:{confirmedBy:actor(q)}});}
    }
    return tx.supplierInvoice.update({where:{id:invoice.id},data:{status:'APPROVED',invoiceKey,approvedBy:actor(q),approvedAt:new Date(),version:{increment:1}}});
  });});
  app.post('/invoices/:id/create-po',async q=>{const {number}=z.object({number:id}).parse(q.body);return mutate(db,q,'Create PO from approved invoice',async tx=>{const invoice=await tx.supplierInvoice.findUniqueOrThrow({where:{id:(q.params as any).id},include});ensure(invoice.status==='APPROVED'&&!invoice.purchaseOrderId,'Approve the invoice first; it must not already have a PO');const po=await tx.purchaseOrder.create({data:{number,supplierId:invoice.supplierId!,currency:invoice.currency,supplierRef:invoice.invoiceNumber,notes:`From approved invoice ${invoice.invoiceNumber}. Delivery still needs to be received.`,lines:{create:invoice.lines.map(l=>({skuId:l.skuId!,supplierCode:l.supplierCode,quantityOrdered:l.quantity!,unitCost:l.unitCost!}))}}});await tx.supplierInvoice.update({where:{id:invoice.id},data:{purchaseOrderId:po.id,version:{increment:1}}});return po;});});
}
