import { createHash, randomBytes } from 'node:crypto';
import { simpleParser } from 'mailparser';
import type { FastifyInstance } from 'fastify';
import type { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { actor, ensure, mutate, transaction } from './core.js';
import { readConnection, saveConnection } from './connections.js';
import { extractDocument } from './invoice-extract.js';
import { ingestInvoice } from './invoices.js';
const providers={GMAIL:{authorize:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',scope:'https://www.googleapis.com/auth/gmail.readonly'},MICROSOFT:{authorize:'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',token:'https://login.microsoftonline.com/common/oauth2/v2.0/token',scope:'offline_access https://graph.microsoft.com/Mail.Read'}};
const configSchema=z.object({provider:z.enum(['GMAIL','MICROSOFT']),clientId:z.string().trim().min(1),clientSecret:z.string().min(1),folder:z.string().trim().min(1).max(200),since:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),senders:z.array(z.string().email()).max(100).default([])});
const states=new Map<string,{expires:number;verifier:string;actor:string;config:any;redirect:string}>();
async function tokenRequest(config:any,params:Record<string,string>){const p=providers[config.provider as keyof typeof providers];const r=await fetch(p.token,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,...params}),signal:AbortSignal.timeout(20000)});ensure(r.ok,`Email sign-in failed (${r.status}). Reconnect the mailbox.`,502);return await r.json() as any;}
async function limited(r:Response){ensure(r.ok,`Email request failed (${r.status})`,502);const chunks:Uint8Array[]=[];let length=0;ensure(r.body,'Empty email response',502);for await(const c of r.body as any){length+=c.length;ensure(length<=12*1024*1024,'Email is larger than the 8 MB import limit',413);chunks.push(c);}return Buffer.concat(chunks);}
export async function registerMailbox(app:FastifyInstance,db:PrismaClient){
  const redirect=()=>{const origin=process.env.WEB_ORIGIN??'http://localhost:4000';const url=new URL(origin);ensure(url.protocol==='https:'||['localhost','127.0.0.1'].includes(url.hostname),'Email connection requires HTTPS or localhost',400);return origin+'/api/mailbox/callback';};
  app.get('/mailbox/status',async q=>{ensure((q as any).user.role==='ADMIN','Administrator access required',403);const row=await db.integrationConnection.findUnique({where:{provider:'MAILBOX'},select:{metadata:true,updatedAt:true}});return {connection:row?.metadata??null,redirectUri:redirect()};});
  app.post('/mailbox/configure',async q=>{const b=configSchema.parse(q.body);return mutate(db,q,'Configure invoice mailbox',async tx=>{await saveConnection(tx,'MAILBOX',b,{provider:b.provider,folder:b.folder,since:b.since,senders:b.senders,connected:false});return {configured:true};});});
  app.post('/mailbox/authorize',async(q,r)=>{const c=await readConnection(db,'MAILBOX');ensure(c,'Configure the mailbox first',400);for(const [k,v]of states)if(v.expires<Date.now())states.delete(k);ensure(states.size<100,'Too many pending connections',429);const state=randomBytes(32).toString('hex'),verifier=randomBytes(32).toString('base64url'),uri=redirect(),p=providers[c.provider as keyof typeof providers];states.set(state,{expires:Date.now()+600000,verifier,actor:actor(q),config:c,redirect:uri});const url=new URL(p.authorize);for(const [k,v]of Object.entries({client_id:c.clientId,redirect_uri:uri,response_type:'code',scope:p.scope,state,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',...(c.provider==='GMAIL'?{access_type:'offline',prompt:'consent'}:{})}))url.searchParams.set(k,String(v));r.header('set-cookie',`erp_mail_oauth=${state}; HttpOnly; SameSite=Lax; Path=/api/mailbox/callback; Max-Age=600${uri.startsWith('https:')?'; Secure':''}`);return {url:url.toString()};});
  app.get('/mailbox/callback',{logLevel:'silent'},async(q,r)=>{const b=z.object({state:z.string(),code:z.string().optional(),error:z.string().optional()}).parse(q.query);const pending=states.get(b.state),cookie=q.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('erp_mail_oauth='))?.slice(15);ensure(pending&&pending.expires>Date.now()&&cookie===b.state,'Email connection expired. Start Connect again.',400);states.delete(b.state);ensure(!b.error&&b.code,'Email permission was not granted',400);ensure(await db.user.findFirst({where:{email:pending.actor,active:true,role:'ADMIN'}}),'Administrator access was revoked',403);const tokens=await tokenRequest(pending.config,{grant_type:'authorization_code',code:b.code,redirect_uri:pending.redirect,code_verifier:pending.verifier});ensure(tokens.refresh_token,'No refresh permission received. Reconnect and allow offline access.',400);const c={...pending.config,refreshToken:tokens.refresh_token};await transaction(db,async tx=>{await saveConnection(tx,'MAILBOX',c,{provider:c.provider,folder:c.folder,since:c.since,senders:c.senders,connected:true,connectedAt:new Date().toISOString()});await tx.auditLog.create({data:{actor:pending.actor,action:'Connect invoice mailbox'}});});return r.header('set-cookie','erp_mail_oauth=; HttpOnly; SameSite=Lax; Path=/api/mailbox/callback; Max-Age=0').header('referrer-policy','no-referrer').redirect('/?section=Invoices');});
  app.delete('/mailbox',async q=>mutate(db,q,'Disconnect invoice mailbox',tx=>tx.integrationConnection.delete({where:{provider:'MAILBOX'}}).then(()=>({disconnected:true}))));
  let running=false;
  app.post('/mailbox/sync',async q=>{
    ensure(!running,'An email import is already running',409);running=true;
    try {
      const c=await readConnection(db,'MAILBOX');ensure(c?.refreshToken,'Connect the invoice mailbox first',400);const tokens=await tokenRequest(c,{grant_type:'refresh_token',refresh_token:c.refreshToken});if(tokens.refresh_token)c.refreshToken=tokens.refresh_token;
      const headers={authorization:'Bearer '+tokens.access_token};let messages:any[]=[];let next:string|null=null;
      if(c.provider==='GMAIL'){
        const url=new URL('https://gmail.googleapis.com/gmail/v1/users/me/messages');url.searchParams.set('maxResults','50');url.searchParams.set('q',`label:"${c.folder.replace(/["\\]/g,'')}" after:${c.since.replaceAll('-','/')}`);if(c.cursor)url.searchParams.set('pageToken',c.cursor);const result=JSON.parse((await limited(await fetch(url,{headers,signal:AbortSignal.timeout(20000)}))).toString());messages=result.messages??[];next=result.nextPageToken??null;
      }else{
        let folderId=c.folderId;if(!folderId){if(c.folder.toLowerCase()==='inbox')folderId='inbox';else {const folders=JSON.parse((await limited(await fetch('https://graph.microsoft.com/v1.0/me/mailFolders?$top=100&$select=id,displayName',{headers,signal:AbortSignal.timeout(20000)}))).toString());const matches=folders.value.filter((f:any)=>f.displayName===c.folder);ensure(matches.length===1,'Choose a unique top-level Outlook folder, or Inbox',400);folderId=matches[0].id;}c.folderId=folderId;}
        const url=c.cursor??`https://graph.microsoft.com/v1.0/me/mailFolders/${encodeURIComponent(folderId)}/messages?$top=50&$select=id,from,receivedDateTime&$filter=${encodeURIComponent(`receivedDateTime ge ${c.since}T00:00:00Z`)}&$orderby=receivedDateTime asc`;
        ensure(url.startsWith('https://graph.microsoft.com/v1.0/'),'Invalid mailbox pagination URL',400);const result=JSON.parse((await limited(await fetch(url,{headers,signal:AbortSignal.timeout(20000)}))).toString());messages=result.value??[];next=result['@odata.nextLink']??null;
      }
      let imported=0,duplicates=0,skipped=0;const errors:string[]=[];
      for(const m of messages){try{
        let raw:Buffer;if(c.provider==='GMAIL'){const data=JSON.parse((await limited(await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(m.id)}?format=raw`,{headers,signal:AbortSignal.timeout(20000)}))).toString());raw=Buffer.from(data.raw,'base64url');}else raw=await limited(await fetch(`https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(m.id)}/$value`,{headers,signal:AbortSignal.timeout(20000)}));
        ensure(raw.length<=8*1024*1024,'Email exceeds 8 MB',413);const mail=await simpleParser(raw,{skipTextToHtml:true,skipImageLinks:true,maxHtmlLengthToParse:2*1024*1024}),sender=mail.from?.value[0]?.address;
        if(c.senders.length&&!c.senders.some((s:string)=>s.toLowerCase()===sender?.toLowerCase())){skipped++;continue;}
        const files=mail.attachments.filter(a=>/\.(pdf|csv|txt)$/i.test(a.filename??''));const inputs=files.length?files.map(a=>({bytes:a.content,filename:a.filename!})):[{bytes:raw,filename:'invoice-email.eml'}];
        for(const input of inputs){const d=await extractDocument(input.bytes,input.filename);d.sender=sender;d.subject=mail.subject;const result=await transaction(db,tx=>ingestInvoice(tx,input.bytes,input.filename,d,c.provider,`${c.provider}:${m.id}`));if(result.duplicate)duplicates++;else imported++;}
      }catch(e){errors.push(`Message ${m.id}: ${(e as Error).message}`);}}
      // Keep failed pages retryable. Deduplication makes retry safe.
      if(!errors.length)c.cursor=next;
      const summary={imported,duplicates,skipped,errors,more:Boolean(next),syncedAt:new Date().toISOString()};await transaction(db,async tx=>{await saveConnection(tx,'MAILBOX',c,{provider:c.provider,folder:c.folder,since:c.since,senders:c.senders,connected:true,lastSync:summary});await tx.auditLog.create({data:{actor:actor(q),action:'Import invoice emails',reference:JSON.stringify(summary)}});});return summary;
    } finally {running=false;}
  });
}
