import type {FastifyInstance} from 'fastify';
import {Prisma,PrismaClient,TrackingMode} from '@prisma/client';
import {z} from 'zod';

const money=(v:number)=>new Prisma.Decimal(v);

export async function registerProcurementRoutes(app:FastifyInstance,db:PrismaClient){
  app.get('/suppliers',async()=>db.supplier.findMany({where:{active:true},include:{supplierSkus:{include:{sku:{include:{family:true}}}},purchaseOrders:{orderBy:{createdAt:'desc'},take:20}},orderBy:{name:'asc'}}));

  app.post('/suppliers',async(q,r)=>{const b=z.object({code:z.string().min(1),name:z.string().min(1),email:z.string().email().optional(),phone:z.string().optional(),website:z.string().optional(),accountNumber:z.string().optional(),notes:z.string().optional()}).parse(q.body);return r.code(201).send(await db.supplier.create({data:b}))});

  app.put('/suppliers/:supplierId/skus/:skuId',async(q,r)=>{const{supplierId,skuId}=z.object({supplierId:z.string(),skuId:z.string()}).parse(q.params);const b=z.object({supplierCode:z.string().optional(),unitCost:z.number().nonnegative().optional(),currency:z.string().default('NZD'),preferred:z.boolean().default(false),leadTimeDays:z.number().int().nonnegative().optional(),minOrderQty:z.number().int().positive().optional()}).parse(q.body);if(b.preferred)await db.supplierSku.updateMany({where:{skuId},data:{preferred:false}});return r.send(await db.supplierSku.upsert({where:{supplierId_skuId:{supplierId,skuId}},create:{supplierId,skuId,supplierCode:b.supplierCode,unitCost:b.unitCost===undefined?undefined:money(b.unitCost),currency:b.currency,preferred:b.preferred,leadTimeDays:b.leadTimeDays,minOrderQty:b.minOrderQty,lastQuotedAt:b.unitCost===undefined?undefined:new Date()},update:{supplierCode:b.supplierCode,unitCost:b.unitCost===undefined?undefined:money(b.unitCost),currency:b.currency,preferred:b.preferred,leadTimeDays:b.leadTimeDays,minOrderQty:b.minOrderQty,lastQuotedAt:b.unitCost===undefined?undefined:new Date()},include:{supplier:true,sku:{include:{family:true}}}}))});

  app.get('/purchase-orders',async()=>db.purchaseOrder.findMany({include:{supplier:true,lines:{include:{sku:{include:{family:true}}}},_count:{select:{lines:true}}},orderBy:{createdAt:'desc'},take:200}));

  app.post('/purchase-orders',async(q,r)=>{const b=z.object({number:z.string().min(1),supplierId:z.string(),currency:z.string().default('NZD'),supplierRef:z.string().optional(),notes:z.string().optional(),expectedAt:z.string().datetime().optional(),lines:z.array(z.object({skuId:z.string(),supplierCode:z.string().optional(),quantityOrdered:z.number().int().positive(),unitCost:z.number().nonnegative()})).min(1)}).parse(q.body);return r.code(201).send(await db.purchaseOrder.create({data:{number:b.number,supplierId:b.supplierId,currency:b.currency,supplierRef:b.supplierRef,notes:b.notes,expectedAt:b.expectedAt?new Date(b.expectedAt):undefined,lines:{create:b.lines.map(l=>({...l,unitCost:money(l.unitCost)}))}},include:{supplier:true,lines:{include:{sku:true}}}}))});

  app.post('/purchase-orders/:id/order',async(q,r)=>{const{id}=z.object({id:z.string()}).parse(q.params);const po=await db.purchaseOrder.findUniqueOrThrow({where:{id}});if(po.status!=='DRAFT')return r.code(409).send({error:'Only draft purchase orders can be ordered'});return r.send(await db.purchaseOrder.update({where:{id},data:{status:'ORDERED',orderedAt:new Date()},include:{supplier:true,lines:{include:{sku:true}}}}))});

  app.post('/purchase-orders/:id/receive',async(q,r)=>{const{id}=z.object({id:z.string()}).parse(q.params);const b=z.object({locationId:z.string(),createdBy:z.string().optional(),lines:z.array(z.object({lineId:z.string(),quantity:z.number().int().positive(),serialNumbers:z.array(z.string()).default([])})).min(1)}).parse(q.body);return r.send(await db.$transaction(async tx=>{const po=await tx.purchaseOrder.findUniqueOrThrow({where:{id},include:{lines:{include:{sku:true}}}});if(['RECEIVED','CANCELLED'].includes(po.status))throw Error('Purchase order cannot be received');for(const input of b.lines){const line=po.lines.find(l=>l.id===input.lineId);if(!line)throw Error(`Unknown PO line ${input.lineId}`);const remaining=line.quantityOrdered-line.quantityReceived;if(input.quantity>remaining)throw Error(`Cannot receive ${input.quantity}; only ${remaining} remaining for ${line.sku.name}`);if(line.sku.trackingMode===TrackingMode.SERIALIZED&&input.serialNumbers.length!==input.quantity)throw Error(`${line.sku.name} requires ${input.quantity} serial number(s)`);if(new Set(input.serialNumbers).size!==input.serialNumbers.length)throw Error(`Duplicate serial numbers for ${line.sku.name}`);await tx.inventoryTransaction.create({data:{skuId:line.skuId,locationId:b.locationId,quantityDelta:input.quantity,type:'PURCHASE_RECEIPT',referenceType:'PURCHASE_ORDER',referenceId:po.id,unitCost:line.unitCost,createdBy:b.createdBy}});if(line.sku.trackingMode===TrackingMode.SERIALIZED)for(const serialNumber of input.serialNumbers)await tx.inventoryUnit.create({data:{skuId:line.skuId,locationId:b.locationId,serialNumber,unitCost:line.unitCost}});await tx.purchaseOrderLine.update({where:{id:line.id},data:{quantityReceived:{increment:input.quantity}}});}
    const fresh=await tx.purchaseOrder.findUniqueOrThrow({where:{id},include:{lines:true}});const complete=fresh.lines.every(l=>l.quantityReceived>=l.quantityOrdered);return tx.purchaseOrder.update({where:{id},data:{status:complete?'RECEIVED':'PARTIALLY_RECEIVED'},include:{supplier:true,lines:{include:{sku:{include:{family:true}}}}}})}))});

  app.get('/procurement/reorder',async()=>{const [stock,reserved,skus,openPo]=await Promise.all([db.inventoryTransaction.groupBy({by:['skuId'],_sum:{quantityDelta:true}}),db.inventoryReservation.groupBy({by:['skuId'],where:{status:'ACTIVE'},_sum:{quantity:true}}),db.sku.findMany({where:{active:true},include:{family:true,supplierSkus:{include:{supplier:true},orderBy:[{preferred:'desc'},{unitCost:'asc'}]}}),db.purchaseOrderLine.groupBy({by:['skuId'],where:{purchaseOrder:{status:{in:['DRAFT','ORDERED','PARTIALLY_RECEIVED']}}},_sum:{quantityOrdered:true,quantityReceived:true}})]);return skus.map(s=>{const onHand=stock.find(x=>x.skuId===s.id)?._sum.quantityDelta??0;const res=reserved.find(x=>x.skuId===s.id)?._sum.quantity??0;const po=openPo.find(x=>x.skuId===s.id);const incoming=(po?._sum.quantityOrdered??0)-(po?._sum.quantityReceived??0);const available=onHand-res;const reorderPoint=Number((s.attributes as any)?.reorderPoint??0);return{sku:s,onHand,reserved:res,available,incoming,reorderPoint,shortage:Math.max(0,reorderPoint-(available+incoming)),preferredSupplier:s.supplierSkus[0]??null}}).filter(x=>x.shortage>0||x.reorderPoint>0).sort((a,b)=>b.shortage-a.shortage)});
}
