import 'dotenv/config';
import {Prisma,PrismaClient} from '@prisma/client';

const db=new PrismaClient();
const createPos=process.argv.includes('--create-pos');
const now=new Date();
const stamp=()=>`${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${Date.now().toString().slice(-6)}`;

async function main(){
  const [stock,reserved,openPo,createdBuilds,skus]=await Promise.all([
    db.inventoryTransaction.groupBy({by:['skuId'],_sum:{quantityDelta:true}}),
    db.inventoryReservation.groupBy({by:['skuId'],where:{status:'ACTIVE'},_sum:{quantity:true}}),
    db.purchaseOrderLine.groupBy({by:['skuId'],where:{purchaseOrder:{status:{in:['DRAFT','ORDERED','PARTIALLY_RECEIVED']}}},_sum:{quantityOrdered:true,quantityReceived:true}}),
    db.build.findMany({where:{status:'CREATED'},include:{lines:true}}),
    db.sku.findMany({where:{active:true},include:{family:true,supplierSkus:{where:{supplier:{active:true}},include:{supplier:true}}},orderBy:{name:'asc'}}),
  ]);

  const demand=new Map<string,number>();
  for(const build of createdBuilds)for(const line of build.lines)if(line.allocatedSkuId)demand.set(line.allocatedSkuId,(demand.get(line.allocatedSkuId)??0)+line.quantity);

  const plan=skus.map(sku=>{
    const onHand=stock.find(x=>x.skuId===sku.id)?._sum.quantityDelta??0;
    const reservedQty=reserved.find(x=>x.skuId===sku.id)?._sum.quantity??0;
    const po=openPo.find(x=>x.skuId===sku.id);
    const incoming=(po?._sum.quantityOrdered??0)-(po?._sum.quantityReceived??0);
    const available=onHand-reservedQty;
    const committedDemand=demand.get(sku.id)??0;
    const safetyStock=Number((sku.attributes as any)?.reorderPoint??0);
    const required=Math.max(0,committedDemand+safetyStock-(available+incoming));
    const offers=sku.supplierSkus.filter(x=>x.unitCost!=null).sort((a,b)=>{
      if(a.preferred!==b.preferred)return a.preferred?-1:1;
      const ac=Number(a.unitCost),bc=Number(b.unitCost);if(ac!==bc)return ac-bc;
      return (a.leadTimeDays??999)-(b.leadTimeDays??999);
    });
    const pick=offers[0]??null;
    const min=pick?.minOrderQty??1;
    const quantity=required?Math.max(required,min):0;
    return{sku,onHand,reserved:reservedQty,available,incoming,committedDemand,safetyStock,required,quantity,pick,offers};
  }).filter(x=>x.required>0).sort((a,b)=>b.required-a.required);

  console.log(`PURCHASE PLAN — ${plan.length} shortage line(s)`);
  if(!plan.length){console.log('No purchasing required.');return}
  let total=0;
  for(const x of plan){
    const cost=x.pick?.unitCost==null?null:Number(x.pick.unitCost);
    if(cost!=null)total+=cost*x.quantity;
    console.log(`${x.sku.name} | need ${x.required} | order ${x.quantity} | avail ${x.available} | incoming ${x.incoming} | build demand ${x.committedDemand} | safety ${x.safetyStock} | ${x.pick?`${x.pick.supplier.name} @ $${cost?.toFixed(2)} (${x.pick.leadTimeDays??'?'}d)`:'NO SUPPLIER COST'}`);
  }
  console.log(`Estimated spend: $${total.toFixed(2)} NZD`);

  if(!createPos){console.log('\nDRY RUN ONLY. To create DRAFT POs grouped by recommended supplier: npm run procurement:plan -- --create-pos');return}
  const actionable=plan.filter(x=>x.pick&&x.pick.unitCost!=null);
  const groups=new Map<string,typeof actionable>();
  for(const x of actionable){const id=x.pick!.supplierId;groups.set(id,[...(groups.get(id)??[]),x])}
  const created=[];
  for(const [supplierId,lines] of groups){
    const supplier=lines[0].pick!.supplier;
    const po=await db.purchaseOrder.create({data:{number:`AUTO-${stamp()}-${supplier.code}`.slice(0,80),supplierId,currency:'NZD',notes:'Generated by Godmode Ops purchase planning engine; requires approval before supplier submission.',lines:{create:lines.map(x=>({skuId:x.sku.id,supplierCode:x.pick!.supplierCode,quantityOrdered:x.quantity,unitCost:new Prisma.Decimal(x.pick!.unitCost!)}))}},include:{supplier:true,lines:{include:{sku:true}}}});
    created.push(po);
  }
  console.log(`\nCreated ${created.length} DRAFT PO(s). No supplier orders were submitted.`);
  for(const po of created)console.log(`${po.number} — ${po.supplier.name} — ${po.lines.length} line(s)`);
}

main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.$disconnect());
